### PR TITLE
Add tests for better handling of focus on the forms

### PR DESCRIPTION
**Pull request by ezhlobo**
Actually, I don't know how to resolve these tests yet. But you probably don't need it.

Anyway, you know better how to resolve them so I'm pushing it to ask your help.

### CODE REVIEW

**Comment by ezhlobo** [comment]
Probably I understand it wrong:

>For dialogs containing a form it could be the first field in the form.

From: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_dialog_role

**Comment by theKashey** [comment]
Second test would not work ;(
It is not hard to implement it, and idea is quite useful. 
The only question - is radio button the only one for this magic.

**Comment by ezhlobo** [comment]
@theKashey I'm not sure about cases other than radio buttons. Can't remember right now.

>Second test would not work ;(

The first test is also failed for me. It returns "third" for some reasons...

>is radio button the only one for this magic

It's actually a default behavior in browsers :)

**Comment by theKashey** [comment]
So first one is a half bug, half a feature :)
FocusLock detect focus leave to the nearest element, like a you just pressed Shift+Tab, and moves focus to the last element.
In the same time it is a bug, cos between `first` and `action1` lays hidden focus-trap, and action1 is not a nearest element...

I should double check this behavior.

**Comment by theKashey** [comment]
I've found a problem with the first test, and gonna to fix it. But to resolve second issue one should first create a proper function.
Like a if chosen element is radio box, then find siblings in the same form, and pick checked one.
Nothing really hard, but let's eat bear in parts... 🐻 

So - merging this PR to test these tests...

**Comment by theKashey** [comment]
@ezhlobo - first test is now green. Second - disabled for now.

**Comment by ezhlobo** [comment]
@theKashey thank you! Could you estimate approximately when the second one can be fixed? This is one which stops me from using this component. 

BTW, let's skip test case with `it.skip` instead of commenting `expect`. Otherwise, it's considered like passed.

**Comment by theKashey** [comment]
@ezhlobo - here is almost Friday, so you can expect an update on Monday.

**Comment by ezhlobo** [comment]
@theKashey have a good weekend, will expect it done on Monday then :)

**Comment by theKashey** [comment]
JFYI: Almost done, just polishing some things.

**Comment by theKashey** [comment]
@ezhlobo 1.4.9 -> 1.5.0
Just wrap your checkboxes with AutoFocusInside, borrowed as named export from focus-lock.

**Pull request merged**
