### PR TITLE
Reduce size

### PR DESCRIPTION
**Pull request by ai**
```diff
-  Package size: 5.88 KB
+  Package size: 4.39 KB
```

1. `setImmediate` forced `@babel/plugin-transform-runtime` to add unnecessary `setImmediate` and `process` polyfills.
2. Rare warning wrapped into `process.env.NODE_ENV !== "production"`
3. `propTypes` wrapping by Babel (machines must suffer)

### CODE REVIEW

**Comment by theKashey** [comment]
Actually that stuff with `setImmediate` was a bit unclear for me. I was not using it, just checking it.

**Comment by theKashey** [comment]
@ai - size did not changed for me. Still 5.89. Even more - I still could see `setImmediate` and `proccess` in "--why".

**Comment by ai** [comment]
> Actually that stuff with setImmediate was a bit unclear for me. I was not using it, just checking it.

It was added by `@babel/plugin-transform-runtime` because it found `setImmediate` in source code.

> size did not changed for me. Still 5.89. Even more - I still could see setImmediate and proccess in "--why".

Di you run `yarn size` to rebuild `dist`?

**Comment by theKashey** [comment]
Sure. I've even published it already :) https://bundlephobia.com/result?p=react-focus-lock@1.17.2

**Comment by ai** [comment]
Maybe we have some difference in how BundlePhobia count the result?

Try to check bundle size of a real project after the update.

**Comment by ai** [comment]
Hm. Seems like I found a reason. npm package contains `dist/es2015/util.js`, so Babel still adds `setImmediate`. Try to clean `dist` before making a release.

**Comment by ai** [comment]
Yeap, there are some problems.

Seems like my Babel hack doesn’t work :(

**Comment by ai** [comment]
Yeap, `setImmediate` polyfill was inserted by Webpack https://github.com/webpack/webpack/issues/4695

**Comment by ai** [comment]
I added issue to webpack https://github.com/webpack/webpack/issues/8280

**Comment by ai** [comment]
I found solution https://github.com/theKashey/react-focus-lock/pull/48 🎉

**Comment by theKashey** [comment]
then I will access `setImmediate` in a more ninja way.

**Comment by krasnoperov** [comment]
JFYI, webpack inserts polyfills for node.js globals: https://webpack.js.org/configuration/node/
This behaviour can be disabled in webpack.config.js:
`{
  // ..
  node: {
    setImmediate: false,
  }
}`

**Comment by ai** [comment]
@krasnoperov we can’t ask every user to change webpack config :(.

**Comment by krasnoperov** [comment]
Sure. I believe that polyfill should be disabled by default.

**Comment by theKashey** [comment]
Look like we are done for today, and magically stripped a few kb. Now I am thinking to run babel on my node-modules, to strip away all not-yet-removed propTypes.

It would also great to create babel or webpack plugin to replace inlined helpers by babel-runtime among each and every file inside node_modules folder. Should be easy, and very effective.

Next iteration, I recon, would be about react hooks, and they will reduce package size a lot.

@ai 💯 
@krasnoperov 👍

**Pull request merged**
