### PR TITLE
Run linter and tests on CircleCI

### LINKED ISSUE #3: Running linter and tests on CI
BTW, what do you think about setting up CircleCI or Travis? They both should be free for open source projects.

It will make this repository more friendly for others and help you to avoid bad code in master.

I can push CircleCI config if you are ok with it. Or let me know what do you think about it.

### PR DESCRIPTION
**Pull request by ezhlobo**
We have discussed it in the issue #3.

I added a basic config for CircleCI. Once you build the project there I'll add badges, so don't merge it.

## To build the project

1. Join via github to https://circleci.com
2. Build the project by opening https://circleci.com/setup-project/gh/theKashey/react-focus-lock

Closes #3

### CODE REVIEW

**Comment by theKashey** [comment]
Look like I have to merge it first, to build it. Default node for circle is v4.

**Comment by theKashey** [comment]
Ok. Ready to merge?
Meanwhile CI failed to install NPM deps.

**Comment by ezhlobo** [comment]
@theKashey well, it's ready. Yeah... Looks like it's failed because it uses old version of node.

**Comment by theKashey** [comment]
@ezhlobo - thank you very-very much.

**Pull request merged**
