### PR TITLE
FocusLock children proptype fixed

### PR DESCRIPTION
**Pull request by NikolaBorislavovHristov**

### CODE REVIEW

**Comment by theKashey** [comment]
Why not wrap whatever you want to pass as children with a Fragment?

**Comment by NikolaBorislavovHristov** [comment]
Can you imagine to pollute your whole codebase with <React.Fragment> around every `.map`?
That would be ridiculous.
Also children should not be required at all, because of the use case they are rendered through the `as` attribute and to suspend the warning i pass `<React.Fragment />` as a children. Which is also ridiculous. :D

**Comment by theKashey** [comment]
I would say - it could be a very bad idea to wrap focus lock (or use any other hard restriction) over something spreaded from `.map`.
However, this sounds quite close to #85 - wrapping _something_ with FocusLock. But before changing anything - let's try to clarify what do you actually need? Could you tell more about your use case?

**Comment by NikolaBorislavovHristov** [comment]
1. drop `required` children prop type
```javascript
const LoginForm = React.forwardRef((props, ref) => {
    return (
        <div {...props} ref={ref}>
            <input className={'login-input'} />
            <input className={'password-input'} />
        </div>
    );
});
const App = () => {
    return <FocusLock as={LoginForm} className={'login-form-container'} />;
};
```
temporary workaround:
```javascript
const App = () => {
    return (
        <FocusLock as={LoginForm} className={'login-form-container'}>
            <React.Fragment/>
        </FocusLock>
    );
};
```
2. add `arrayOf(node)` to children prop type
```javascript
const App = () => {
    return (
        <FocusLock as={'ul'} className={'menu'}>
            {menuOptions.map((option) => <li key={option}>{option}</li>)
        </FocusLock>
    );
};
```
temporary workaround:
```javascript
const App = () => {
    return (
        <FocusLock as={'ul'} className={'menu'}>
            <React.Fragment>
                {menuOptions.map((option) => <li key={option}>{option}</li>)
            </React.Fragment>
        </FocusLock>
    );
};
```

**Comment by theKashey** [comment]
In both cases "the problem" is driven by the use of the `as` prop. Why you really need to use it?
Please take me right - during the past year, we had a few incidents when Focus/Scroll lock was doing their job too good, blocking business processes - locks are very dangerous things, and should not be "just" used here and there.

**Comment by NikolaBorislavovHristov** [comment]
i dont see how changing children prop type affects the functionality of this package. after all the focus lock component needs a valid ref to the container dom element wcich i provide through the as prop with forward ref. i really wanted to avoid that additional div and deploy an application with 0 error logs. so the choices i have are to use redicilous fragments and leave a comment about what i am trying to do or use fork.

**Comment by theKashey** [comment]
Just checking what shall be changed, and look like `PropTypes.node` or `ReactNode` are supporting arrays out of the box, so the change to propTypes is not required. As well it shall not be `required`, as long as `children` is a property of Container passed via `as`, and it's not up to FocusLock to control or restrict it.

However, there is one restriction, which was added unintentionally - `Sidecar` (lock's logic) is also inside the container. And so - if by any reason you will not render provided `children` - it would not work at all.

So:
- move `Sidecar` out of `Container`
- remove restrictions from PropTypes
- for TS - infer the right children type

**Pull request closed without merging**
